Data Generation
===

In [1]:
import numpy as np

In [2]:
num_samples, num_features = 10, 5

In [4]:
data = np.random.rand(num_samples, num_features)
data

array([[ 0.03922382,  0.54600794,  0.84755044,  0.75014668,  0.92066044],
       [ 0.20232815,  0.10368315,  0.63236762,  0.73168421,  0.47554526],
       [ 0.48158561,  0.5580223 ,  0.87792689,  0.85032364,  0.42473651],
       [ 0.98553674,  0.27664415,  0.38443798,  0.76724864,  0.40859603],
       [ 0.30330109,  0.86258683,  0.59435667,  0.52828942,  0.74262187],
       [ 0.6584849 ,  0.14682076,  0.7752057 ,  0.31090843,  0.51431686],
       [ 0.47671075,  0.71762038,  0.16035897,  0.0167796 ,  0.15191394],
       [ 0.26930333,  0.05844265,  0.55306294,  0.07169883,  0.38777526],
       [ 0.17417705,  0.69118323,  0.37231383,  0.544765  ,  0.50660424],
       [ 0.14741817,  0.768586  ,  0.41531449,  0.02920173,  0.69171461]])

Solution
===

In [5]:
print(data)

[[ 0.03922382  0.54600794  0.84755044  0.75014668  0.92066044]
 [ 0.20232815  0.10368315  0.63236762  0.73168421  0.47554526]
 [ 0.48158561  0.5580223   0.87792689  0.85032364  0.42473651]
 [ 0.98553674  0.27664415  0.38443798  0.76724864  0.40859603]
 [ 0.30330109  0.86258683  0.59435667  0.52828942  0.74262187]
 [ 0.6584849   0.14682076  0.7752057   0.31090843  0.51431686]
 [ 0.47671075  0.71762038  0.16035897  0.0167796   0.15191394]
 [ 0.26930333  0.05844265  0.55306294  0.07169883  0.38777526]
 [ 0.17417705  0.69118323  0.37231383  0.544765    0.50660424]
 [ 0.14741817  0.768586    0.41531449  0.02920173  0.69171461]]


In [6]:
np.mean(data, axis=0)

array([ 0.37380696,  0.47295974,  0.56128955,  0.46010462,  0.5224485 ])

In [9]:
centered_data = data - np.mean(data, axis=0)
np.mean(centered_data, axis=0)

array([  1.11022302e-17,   4.44089210e-17,  -5.55111512e-17,
        -2.22044605e-17,  -3.33066907e-17])

In [10]:
std_data = centered_data / np.std(centered_data, axis=0)

In [11]:
print(std_data)
print('\n')
print(np.mean(std_data, axis=0))
print(np.std(std_data, axis=0))

[[-1.24191941  0.25629335  1.30223535  0.9304838   1.95201951]
 [-0.63650206 -1.2956258   0.32334273  0.87125433 -0.22991787]
 [ 0.40005721  0.29844636  1.4404215   1.25186145 -0.47898038]
 [ 2.27064365 -0.6887833  -0.80451916  0.98534857 -0.55810042]
 [-0.26170658  1.36702658  0.15042631  0.21874361  1.07928132]
 [ 1.05667923 -1.14427529  0.97313041 -0.4786362  -0.03986099]
 [ 0.3819625   0.85840438 -1.82388166 -1.42223075 -1.81634607]
 [-0.38790086 -1.45435443 -0.03742387 -1.2460444  -0.66016304]
 [-0.74099449  0.76564827 -0.85967339  0.27159893 -0.07766796]
 [-0.84031919  1.03721987 -0.66405821 -1.38237932  0.82973589]]


[  1.11022302e-17   1.33226763e-16  -1.99840144e-16   0.00000000e+00
  -1.22124533e-16]
[ 1.  1.  1.  1.  1.]
