Data Generation
===

In [2]:
import numpy as np
import itertools

In [4]:
p, q = (np.random.rand(i, 2) for i in (4, 5))

print(p, "\n\n", q)

[[ 0.22665952  0.76053546]
 [ 0.01665229  0.80832522]
 [ 0.4633109   0.68082056]
 [ 0.73680407  0.67818728]] 

 [[ 0.51077588  0.8847029 ]
 [ 0.69688097  0.81875422]
 [ 0.48300976  0.19948024]
 [ 0.68153041  0.14995426]
 [ 0.48476282  0.3951631 ]]


Solution
===

In [6]:
pairs = list(itertools.product(range(len(p)), range(len(q))))

print(pairs)

[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4)]


In [8]:
p_inds, q_inds = zip(*pairs)

print(p_inds, "\n\n", q_inds)

(0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3) 

 (0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4)


In [9]:
p[p_inds, :]

array([[ 0.22665952,  0.76053546],
       [ 0.22665952,  0.76053546],
       [ 0.22665952,  0.76053546],
       [ 0.22665952,  0.76053546],
       [ 0.22665952,  0.76053546],
       [ 0.01665229,  0.80832522],
       [ 0.01665229,  0.80832522],
       [ 0.01665229,  0.80832522],
       [ 0.01665229,  0.80832522],
       [ 0.01665229,  0.80832522],
       [ 0.4633109 ,  0.68082056],
       [ 0.4633109 ,  0.68082056],
       [ 0.4633109 ,  0.68082056],
       [ 0.4633109 ,  0.68082056],
       [ 0.4633109 ,  0.68082056],
       [ 0.73680407,  0.67818728],
       [ 0.73680407,  0.67818728],
       [ 0.73680407,  0.67818728],
       [ 0.73680407,  0.67818728],
       [ 0.73680407,  0.67818728]])

In [16]:
distances = np.sqrt(np.sum((p[p_inds, :] - q[q_inds, :])**2, axis=1)) # alternatively np.linalg.norm

print(distances)

[ 0.31006396  0.47381182  0.61684552  0.76139144  0.44734134  0.49999167
  0.68030862  0.76692992  0.93568972  0.62436401  0.2093345   0.27125757
  0.48174324  0.57396759  0.28646182  0.30616572  0.14612638  0.54182283
  0.53111703  0.37898216]


In [18]:
distances = np.reshape(distances, (len(p), len(q)))

print(distances)

[[ 0.31006396  0.47381182  0.61684552  0.76139144  0.44734134]
 [ 0.49999167  0.68030862  0.76692992  0.93568972  0.62436401]
 [ 0.2093345   0.27125757  0.48174324  0.57396759  0.28646182]
 [ 0.30616572  0.14612638  0.54182283  0.53111703  0.37898216]]
