Data Generation
===

In [40]:
import numpy as np
import itertools

In [42]:
p_num = 4
q_num = 5
p, q = (np.random.rand(i, 2) for i in (p_num, q_num))

print(p) # 4 x 2 matrix
print('\n')
print(q) # 5 x 2 matrix

[[ 0.5770211   0.43727208]
 [ 0.2075602   0.96563561]
 [ 0.89974397  0.71276513]
 [ 0.45142461  0.46265782]]


[[ 0.06996521  0.57177429]
 [ 0.03982235  0.80206858]
 [ 0.97983539  0.05024302]
 [ 0.19862208  0.31296209]
 [ 0.24386778  0.137138  ]]


Solution
===

In [43]:
pairs = list(itertools.product(range(len(p)), range(len(q)))) # cartesian product of two sets

print(pairs)

[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4)]


In [44]:
map(lambda x : x[0], pairs) # retrieve list of first elements from list of pairs

[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3]

In [45]:
p_inds, q_inds = zip(*pairs) # Use * to unzip. Remove it to perform zip.

print(p_inds)
print(q_inds)

(0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3)
(0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4)


In [36]:
p[p_inds, :]

array([[ 0.98254819,  0.8043184 ],
       [ 0.98254819,  0.8043184 ],
       [ 0.98254819,  0.8043184 ],
       [ 0.98254819,  0.8043184 ],
       [ 0.98254819,  0.8043184 ],
       [ 0.06555706,  0.59702304],
       [ 0.06555706,  0.59702304],
       [ 0.06555706,  0.59702304],
       [ 0.06555706,  0.59702304],
       [ 0.06555706,  0.59702304],
       [ 0.06873029,  0.722863  ],
       [ 0.06873029,  0.722863  ],
       [ 0.06873029,  0.722863  ],
       [ 0.06873029,  0.722863  ],
       [ 0.06873029,  0.722863  ],
       [ 0.7728948 ,  0.87390383],
       [ 0.7728948 ,  0.87390383],
       [ 0.7728948 ,  0.87390383],
       [ 0.7728948 ,  0.87390383],
       [ 0.7728948 ,  0.87390383]])

In [46]:
distances = np.sum((p[p_inds, :] - q[q_inds, :])**2, axis=1) # alternatively np.linalg.norm

print(distances)

[ 0.27519652  0.42165898  0.31205084  0.15863879  0.2010716   0.17405912
  0.05489016  1.43435256  0.42606262  0.68772654  0.7084112   0.74744029
  0.44535018  0.65141437  0.76152017  0.15741768  0.28461608  0.44930392
  0.08631793  0.14904299]


In [47]:
distances = np.reshape(distances, (len(p), len(q)))

print(distances)

[[ 0.27519652  0.42165898  0.31205084  0.15863879  0.2010716 ]
 [ 0.17405912  0.05489016  1.43435256  0.42606262  0.68772654]
 [ 0.7084112   0.74744029  0.44535018  0.65141437  0.76152017]
 [ 0.15741768  0.28461608  0.44930392  0.08631793  0.14904299]]


In [48]:
# Alternative solution:

(-2 * p.dot(q.T)) + np.sum(p**2, axis = 1).reshape((4, 1))  + np.sum(q**2, axis = 1).reshape((1,5))

array([[ 0.27519652,  0.42165898,  0.31205084,  0.15863879,  0.2010716 ],
       [ 0.17405912,  0.05489016,  1.43435256,  0.42606262,  0.68772654],
       [ 0.7084112 ,  0.74744029,  0.44535018,  0.65141437,  0.76152017],
       [ 0.15741768,  0.28461608,  0.44930392,  0.08631793,  0.14904299]])