Numpy Primer
============

In [1]:
import numpy as np

In [2]:
np.zeros(4)

array([ 0.,  0.,  0.,  0.])

In [3]:
np.zeros((2, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [4]:
np.ones((2, 4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [5]:
np.ones((2, 4)) * 3

array([[ 3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.]])

In [6]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [7]:
np.random.randn(3, 4) # normal distributed values

array([[ 0.01641568, -0.71948105,  0.30918198, -2.12931333],
       [-0.50339823,  0.97977625,  0.2406688 ,  0.30511084],
       [ 1.02167086, -0.2782593 , -0.49056255, -1.00855745]])

In [8]:
list(range(4))

[0, 1, 2, 3]

In [9]:
np.arange(4)

array([0, 1, 2, 3])

In [10]:
a = np.array([[1.0, 2.0], [5.0, 4.0]])

In [11]:
b = np.array([[4, 3], [2, 1]])

In [12]:
print(b.dtype, a.dtype) # each array has a data type (casting rules apply for int -> float)

(dtype('int64'), dtype('float64'))


In [13]:
v = np.array([0.5, 2.0])

In [14]:
np.array(["Mickey", "Mouse"]) # can hold more than just numbers

array(['Mickey', 'Mouse'], 
      dtype='|S6')

In [15]:
a

array([[ 1.,  2.],
       [ 5.,  4.]])

In [16]:
np.transpose(a) 

array([[ 1.,  5.],
       [ 2.,  4.]])

In [17]:
a.T # shorthand

array([[ 1.,  5.],
       [ 2.,  4.]])

In [18]:
a.diagonal(0) # first diagonal

array([ 1.,  4.])

In [19]:
a.shape # returns a regular python tuple

(2, 2)

In [20]:
a.shape[0]

2

In [21]:
v.shape

(2,)

In [22]:
np.sum(a), np.sum(a, axis=0), np.sum(a, axis=1) # reduce-operations reduce the whole array if no axis is specified

(12.0, array([ 6.,  6.]), array([ 3.,  9.]))

In [23]:
np.max(a, axis=1), np.mean(a, axis=0)

(array([ 2.,  5.]), array([ 3.,  3.]))

In [24]:
np.linalg.inv(a) 

array([[-0.66666667,  0.33333333],
       [ 0.83333333, -0.16666667]])

In [25]:
np.dot(a, b) # matrix multiplication

array([[  8.,   5.],
       [ 28.,  19.]])

In [26]:
a.dot(b) #shorthand

array([[  8.,   5.],
       [ 28.,  19.]])

In [27]:
a.dot(np.linalg.inv(a)) # should be the identity matrix

array([[  1.00000000e+00,   0.00000000e+00],
       [ -4.44089210e-16,   1.00000000e+00]])

In [28]:
a * b # math operations are element-wise

array([[  4.,   6.],
       [ 10.,   4.]])

In [29]:
a - b

array([[-3., -1.],
       [ 3.,  3.]])

In [30]:
np.linalg.solve(a, v) # solves ax = v

array([ 0.33333333,  0.08333333])

In [31]:
np.reshape(a, (1, 4))

array([[ 1.,  2.,  5.,  4.]])

In [32]:
np.reshape(a, (4,)), np.ravel(a) # flattening

(array([ 1.,  2.,  5.,  4.]), array([ 1.,  2.,  5.,  4.]))

In [33]:
a.reshape((4, 1))

array([[ 1.],
       [ 2.],
       [ 5.],
       [ 4.]])

In [34]:
a.reshape((-1, 1)) # a[-1] means 'whatever needs to go there'

array([[ 1.],
       [ 2.],
       [ 5.],
       [ 4.]])

In [35]:
np.hstack([a, b])

array([[ 1.,  2.,  4.,  3.],
       [ 5.,  4.,  2.,  1.]])

In [36]:
np.vstack([a, b])

array([[ 1.,  2.],
       [ 5.,  4.],
       [ 4.,  3.],
       [ 2.,  1.]])

In [37]:
np.vstack([a, b]) + v # broadcasting

array([[ 1.5,  4. ],
       [ 5.5,  6. ],
       [ 4.5,  5. ],
       [ 2.5,  3. ]])

In [38]:
np.hstack([a, b]) + v # does not work

ValueError: operands could not be broadcast together with shapes (2,4) (2,) 

In [39]:
np.hstack([a, b]) + v.T # transposing a 1-D array achieves nothing

ValueError: operands could not be broadcast together with shapes (2,4) (2,) 

In [40]:
np.hstack([a, b]) + v.reshape((-1, 1)) # reshaping to convert v from a (2,) vector to a (2,1) matrix

array([[ 1.5,  2.5,  4.5,  3.5],
       [ 7. ,  6. ,  4. ,  3. ]])

In [41]:
np.hstack([a, b]) + v[:, np.newaxis] # equivalently, we can add an axis

array([[ 1.5,  2.5,  4.5,  3.5],
       [ 7. ,  6. ,  4. ,  3. ]])

In [42]:
np.dstack([a, b]) # 

array([[[ 1.,  4.],
        [ 2.,  3.]],

       [[ 5.,  2.],
        [ 4.,  1.]]])

In [43]:
np.dstack([a, b]).shape

(2, 2, 2)

In [44]:
r = np.random.random_integers(0, 9, size=(3, 4))

In [45]:
r

array([[3, 9, 8, 9],
       [3, 1, 6, 1],
       [0, 5, 6, 1]])

In [46]:
r[0], r[1]

(array([3, 9, 8, 9]), array([3, 1, 6, 1]))

In [47]:
r[0:2]

array([[3, 9, 8, 9],
       [3, 1, 6, 1]])

In [48]:
r[1][2] # regular python

6

In [49]:
r[1, 2] # numpy

6

In [50]:
r[:, 1:3]

array([[9, 8],
       [1, 6],
       [5, 6]])

In [51]:
r > 5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [False, False,  True, False]], dtype=bool)

In [52]:
r[r > 5]

array([9, 8, 9, 6, 6])

In [53]:
r[r > 5] = 999

In [54]:
r

array([[  3, 999, 999, 999],
       [  3,   1, 999,   1],
       [  0,   5, 999,   1]])