Numpy Primer
============

In [1]:
import numpy as np

In [2]:
np.zeros(4)

array([ 0.,  0.,  0.,  0.])

In [3]:
np.zeros((2, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [4]:
np.ones((2, 4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [5]:
np.ones((2, 4)) * 3

array([[ 3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.]])

In [6]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [7]:
np.random.randn(3, 4) # normal distributed values

array([[ 1.18804593,  0.70082362, -0.08712037,  0.34715501],
       [ 1.27397682, -0.06231991,  0.414075  ,  0.81958578],
       [-0.40458011, -1.02699072, -0.05776944, -0.38177585]])

In [8]:
list(range(4))

[0, 1, 2, 3]

In [9]:
np.arange(4)

array([0, 1, 2, 3])

In [10]:
a = np.array([[1.0, 2.0], [5.0, 4.0]])

In [11]:
b = np.array([[4, 3], [2, 1]])

In [12]:
print(b.dtype, a.dtype) # each array has a data type (casting rules apply for int -> float)

int64 float64


In [13]:
c = np.arange(10)

In [14]:
c[:3], c[2:4], c[7:], c[-3:], c[1:5:2], c[::-1] # basic indexing as in python

(array([0, 1, 2]),
 array([2, 3]),
 array([7, 8, 9]),
 array([7, 8, 9]),
 array([1, 3]),
 array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))

In [15]:
np.array(["Mickey", "Mouse"]) # can hold more than just numbers

array(['Mickey', 'Mouse'], 
      dtype='<U6')

In [16]:
a

array([[ 1.,  2.],
       [ 5.,  4.]])

In [17]:
a[0] # an array is just a list of lists (of lists of lists ...)

array([ 1.,  2.])

In [18]:
np.transpose(a) 

array([[ 1.,  5.],
       [ 2.,  4.]])

In [19]:
a.T # shorthand

array([[ 1.,  5.],
       [ 2.,  4.]])

In [20]:
a.diagonal(0) # first diagonal

array([ 1.,  4.])

In [21]:
a.shape # returns a regular python tuple

(2, 2)

In [22]:
a.shape[0]

2

In [23]:
v = np.array([0.5, 2.0])

In [24]:
v.shape

(2,)

In [25]:
np.sqrt(a) # universal functions operate element-wise

array([[ 1.        ,  1.41421356],
       [ 2.23606798,  2.        ]])

In [26]:
np.sum(a), np.sum(a, axis=0), np.sum(a, axis=1) # reduce-operations reduce the whole array if no axis is specified

(12.0, array([ 6.,  6.]), array([ 3.,  9.]))

In [27]:
np.max(a, axis=1), np.mean(a, axis=0)

(array([ 2.,  5.]), array([ 3.,  3.]))

In [28]:
np.linalg.inv(a) 

array([[-0.66666667,  0.33333333],
       [ 0.83333333, -0.16666667]])

In [29]:
np.dot(a, b) # matrix multiplication

array([[  8.,   5.],
       [ 28.,  19.]])

In [30]:
a.dot(b) #shorthand

array([[  8.,   5.],
       [ 28.,  19.]])

In [31]:
a.dot(np.linalg.inv(a)) # should be the identity matrix

array([[  1.00000000e+00,   0.00000000e+00],
       [ -4.44089210e-16,   1.00000000e+00]])

In [32]:
a * b # math operations are element-wise

array([[  4.,   6.],
       [ 10.,   4.]])

In [33]:
a - b

array([[-3., -1.],
       [ 3.,  3.]])

In [34]:
np.linalg.solve(a, v) # solves ax = v

array([ 0.33333333,  0.08333333])

In [35]:
np.reshape(a, (1, 4))

array([[ 1.,  2.,  5.,  4.]])

In [36]:
np.reshape(a, (4,)), np.ravel(a) # flattening

(array([ 1.,  2.,  5.,  4.]), array([ 1.,  2.,  5.,  4.]))

In [37]:
a.reshape((4, 1))

array([[ 1.],
       [ 2.],
       [ 5.],
       [ 4.]])

In [38]:
a.reshape((-1, 1)) # a[-1] means 'whatever needs to go there'

array([[ 1.],
       [ 2.],
       [ 5.],
       [ 4.]])

In [39]:
np.hstack([a, b])

array([[ 1.,  2.,  4.,  3.],
       [ 5.,  4.,  2.,  1.]])

In [40]:
np.vstack([a, b])

array([[ 1.,  2.],
       [ 5.,  4.],
       [ 4.,  3.],
       [ 2.,  1.]])

In [41]:
np.vstack([a, b]) + v # broadcasting

array([[ 1.5,  4. ],
       [ 5.5,  6. ],
       [ 4.5,  5. ],
       [ 2.5,  3. ]])

In [43]:
np.hstack([a, b]) + v # does not work

ValueError: operands could not be broadcast together with shapes (2,4) (2,) 

In [44]:
np.hstack([a, b]) + v.T # transposing a 1-D array achieves nothing

ValueError: operands could not be broadcast together with shapes (2,4) (2,) 

In [45]:
np.hstack([a, b]) + v.reshape((-1, 1)) # reshaping to convert v from a (2,) vector to a (2,1) matrix

array([[ 1.5,  2.5,  4.5,  3.5],
       [ 7. ,  6. ,  4. ,  3. ]])

In [46]:
np.hstack([a, b]) + v[:, np.newaxis] # equivalently, we can add an axis

array([[ 1.5,  2.5,  4.5,  3.5],
       [ 7. ,  6. ,  4. ,  3. ]])

In [47]:
np.dstack([a, b]) # stack in depth (axis 2)

array([[[ 1.,  4.],
        [ 2.,  3.]],

       [[ 5.,  2.],
        [ 4.,  1.]]])

In [48]:
np.dstack([a, b]).shape

(2, 2, 2)

In [49]:
r = np.random.randint(0, 10, size=(3, 4))

In [50]:
r

array([[6, 5, 2, 5],
       [3, 0, 2, 5],
       [4, 2, 5, 0]])

In [51]:
r[0], r[1]

(array([6, 5, 2, 5]), array([3, 0, 2, 5]))

In [52]:
r[0:2]

array([[6, 5, 2, 5],
       [3, 0, 2, 5]])

In [53]:
r[1][2] # regular python

2

In [54]:
r[1, 2] # numpy

2

In [55]:
r[:, 1:3]

array([[5, 2],
       [0, 2],
       [2, 5]])

In [56]:
r > 5

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False]], dtype=bool)

In [57]:
r[r > 5]

array([6])

In [58]:
r[r > 5] = 999

In [59]:
r

array([[999,   5,   2,   5],
       [  3,   0,   2,   5],
       [  4,   2,   5,   0]])

In [60]:
N, d, sigma = 1000, 50, 6.
Xpos = np.random.multivariate_normal(np.ones(d), np.eye(d) * sigma, N)
Xneg = np.random.multivariate_normal(-np.ones(d), np.eye(d) * sigma, N)
X = np.concatenate((Xpos, Xneg))
Y = np.concatenate((np.ones(N), np.zeros(N)))
inds = np.arange(2*N)
np.random.shuffle(inds)
X, Y = X[inds], Y[inds]

In [61]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y)

svm = SVC()
svm.fit(X_train, Y_train)
Y_pred = svm.predict(X_test)
print(np.mean(Y_pred == Y_test))

0.73
